name: Run Tourism Safety News Job

on:
  schedule:
    # Run every day at 06:00 UTC
    - cron: "0 6 * * *"
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          db_key: ${{ secrets.db_key }}
        run: python app.py
